### ISSUE TITLE
[Design] Custom Star Slider 제작

### ISSUE THREAD

**Issue by i-colours-u** [Health-Food-Me/Health-Food-Me-iOS#49]
## 🛠 Issue

<img width="502" alt="스크린샷 2022-07-13 오후 8 24 39" src="https://user-images.githubusercontent.com/60260284/178722963-7b9f24d5-a56a-4ce2-94c1-a5d766d6a6fb.png">

## 📝 To-do

Slider 형태로 Star 값을 조정할 수 있도록 처리합니다
- [x] 기존에 제작된 StarView와 UISlider를 묶어서 Star Slider를 제작합니다.

**Comment by L-j-h-c** [comment]
기존에 만들어 둔 StarView에서 starScale에 값을 지정해주면 스택뷰 영역이 이상하게 잡히는데 혹시 봐주실 수 있을까요...? ㅎㅎ
